const fs = require('fs');
const path = require('path');

let env = {};

// 1. Read .env file if it exists
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
  try {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const parts = trimmed.split('=');
        const key = parts[0].trim();
        const value = parts.slice(1).join('=').trim();
        if (key) {
          env[key] = value;
        }
      }
    });
  } catch (err) {
    console.warn('Could not read local .env file:', err.message);
  }
}

// 2. Read process.env values (takes precedence)
const supabaseUrl = process.env.SUPABASE_URL || env.SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_KEY || env.SUPABASE_KEY || '';

// 3. Write output to js/config.js
const configDir = path.join(__dirname, 'js');
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir);
}

const configContent = `// Autogenerated configuration - DO NOT COMMIT TO SOURCE CONTROL
window.ENV = {
  SUPABASE_URL: ${JSON.stringify(supabaseUrl)},
  SUPABASE_KEY: ${JSON.stringify(supabaseKey)}
};
`;

try {
  fs.writeFileSync(path.join(configDir, 'config.js'), configContent, 'utf8');
  console.log('Successfully generated js/config.js');
} catch (err) {
  console.error('Failed to write js/config.js:', err.message);
  process.exit(1);
}
